sudo: false
language: python
python: pypy
install: pip install tox
script: tox
matrix:
  fast_finish: true
  include:
    - python: "pypy"
      env: TOXENV=pypy
    - python: "3.5"
      env: TOXENV=py35
